# Generated by Django 4.2 on 2024-08-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_surveyresponse_therapy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='username',
        ),
    ]
