# Generated by Django 4.2 on 2024-08-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_patient_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='username',
            new_name='name',
        ),
    ]
